name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '*.md'

concurrency: 
  group: "build"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Gradle
      run: ./gradlew assembleRelease
    - name: push build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "pre-release"
        prerelease: false
        title: "Build"
        files: |
          app/build/outputs/apk/release/*.apk
